// <auto-generated />
using System;
using Cqs.CoreSampleLib.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cqs.CoreSampleLib.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cqs.CoreSampleLib.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Authors");

                    b.Property<DateTime>("DatePublished");

                    b.Property<bool>("InMyPossession");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Authors = "J.R.Tolkien",
                            DatePublished = new DateTime(2010, 12, 21, 18, 16, 7, 581, DateTimeKind.Utc).AddTicks(8960),
                            InMyPossession = true,
                            Title = "Lord of the Rings"
                        },
                        new
                        {
                            Id = 2,
                            Authors = "Blake Harris",
                            DatePublished = new DateTime(2010, 12, 21, 18, 16, 7, 582, DateTimeKind.Utc).AddTicks(1299),
                            InMyPossession = true,
                            Title = "The History of the Future"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
